version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    #image: postgres:latest
    build:
      context: ./postgres-db/config
      dockerfile: ./Dockerfile
    image: ad_postgres:latest
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
